CREATE TABLE public.tweet
(
    id             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    twitter_id     int8 NULL,
    text         varchar(255) NULL,
    resource_url   varchar(255) NULL,
    username       varchar(255) NULL,
    scheduled_date timestamp NULL,
    creation_date  timestamp NULL,
    update_date    timestamp NULL,
    deleted_date   timestamp NULL,
    CONSTRAINT tweet_pkey PRIMARY KEY (id)
);