ALTER TABLE public.tweet
DROP CONSTRAINT fk_tweet_resource;

ALTER TABLE public.tweet
DROP COLUMN resource_id;

DROP TABLE public.resource;

CREATE TABLE public.resource
(
    id             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url            varchar(255) NULL,
    tweet_id       int8 NULL,
    creation_date  timestamp NULL,
    deleted_date   timestamp NULL,
    CONSTRAINT resource_pkey PRIMARY KEY (id),
    CONSTRAINT fk_resource_tweet FOREIGN KEY (tweet_id) REFERENCES public.tweet (id)
);
