CREATE TABLE public.instagram
(
    id             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    instagram_id   int8 NULL,
    text           varchar(255) NULL,
    resource_id    int8 NULL,
    username       varchar(255) NULL,
    scheduled_date timestamp NULL,
    creation_date  timestamp NULL,
    update_date    timestamp NULL,
    CONSTRAINT instagram_pkey PRIMARY KEY (id)
);

ALTER TABLE public.resource
ADD COLUMN instagram_id int8;

ALTER TABLE public.resource
ADD CONSTRAINT fk_resource_instagram FOREIGN KEY (instagram_id) REFERENCES public.instagram (id);